## WELCOME NUMPY TUTORIAL

In [1]:
import numpy as np

In [2]:
myarr= np.array([[4,5,8,6]], np.int8)

In [3]:
myarr.shape

(1, 4)

In [4]:
myarr.dtype

dtype('int8')

In [5]:
myarr[0,1] 

np.int8(5)

In [6]:
myarr[0,1]=55

In [7]:
myarr

array([[ 4, 55,  8,  6]], dtype=int8)

## Array Creation: Conversion from other Python structures

In [8]:
listarray=np.array([[1,4,3], [5,7,2],[9,3,6]])

In [9]:
listarray

array([[1, 4, 3],
       [5, 7, 2],
       [9, 3, 6]])

In [10]:
listarray.dtype

dtype('int64')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({33,98,67})

array({33, 98, 67}, dtype=object)

In [14]:
zeros=np.zeros((2,4))

In [15]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
range=np.arange(12)

In [18]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
lspace=np.linspace(1,5,4)

In [20]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [21]:
emp=np.empty((4,6))

In [22]:
emp

array([[ 1.05789962e-311,  1.05789962e-311,  1.05789962e-311,
         1.05789962e-311,  1.05789962e-311,  1.05789962e-311],
       [ 1.05789962e-311,  1.05789962e-311,  1.05789961e-311,
         1.05789962e-311,  1.05789962e-311,  1.05789962e-311],
       [ 1.05789962e-311,  1.05789961e-311,  1.05789962e-311,
         1.05789962e-311,  1.05789961e-311,  1.05789962e-311],
       [ 1.05789962e-311, -9.77848868e-311,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [23]:
emp_like=np.empty_like((lspace))

In [24]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [25]:
ide=np.identity(50)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(50, 50))

In [27]:
ide.shape

(50, 50)

In [28]:
Array=np.arange((100))

In [29]:
Array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
Array=Array.reshape(5,20)

In [31]:
Array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [32]:
Array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [33]:
Array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
Array.shape

(5, 20)

In [35]:
x=[[2,4,5],[5,3,9],[11,4,1]]

In [36]:
ar=np.array(x)

In [37]:
ar

array([[ 2,  4,  5],
       [ 5,  3,  9],
       [11,  4,  1]])

In [38]:
ar.sum(axis=0)      ## add column

array([18, 11, 15])

In [39]:
ar.sum(axis=1)    ## add row

array([11, 17, 16])

In [40]:
ar.T         ## transpose the array

array([[ 2,  5, 11],
       [ 4,  3,  4],
       [ 5,  9,  1]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:     ## total items prints in my array
    print(item)

2
4
5
5
3
9
11
4
1


In [43]:
ar.ndim         ## no. of daimension

2

In [44]:
ar.size        ## How many elements in my array

9

In [45]:
ar.nbytes      ## total bytes consume in my array

72

In [46]:
one=np.array([2,8,443,32,111])

In [47]:
one.argmax()      ## index where your max value

np.int64(2)

In [48]:
one.argmin()          ## index where your min value

np.int64(0)

In [49]:
one.argsort()

array([0, 1, 3, 4, 2])

In [50]:
ar

array([[ 2,  4,  5],
       [ 5,  3,  9],
       [11,  4,  1]])

In [51]:
ar.argmin()

np.int64(8)

In [52]:
ar.argmax()

np.int64(6)

In [53]:
ar.argmax(axis=0)

array([2, 0, 1])

In [54]:
ar.argmax(axis=1)

array([2, 2, 0])

In [55]:
ar.argsort(axis=0)

array([[0, 1, 2],
       [1, 0, 0],
       [2, 2, 1]])

In [56]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0]])

In [57]:
ar.ravel()     ## straight the array

array([ 2,  4,  5,  5,  3,  9, 11,  4,  1])

In [58]:
ar

array([[ 2,  4,  5],
       [ 5,  3,  9],
       [11,  4,  1]])

In [59]:
ar2=np.array([[1,5,6],[3,7,9],[1,4,3]])

In [60]:
ar+ar2

array([[ 3,  9, 11],
       [ 8, 10, 18],
       [12,  8,  4]])

In [61]:
[125,44]+[55,85]

[125, 44, 55, 85]

In [62]:
ar*ar2       ## multiply the array element wise

array([[ 2, 20, 30],
       [15, 21, 81],
       [11, 16,  3]])

In [63]:
ar

array([[ 2,  4,  5],
       [ 5,  3,  9],
       [11,  4,  1]])

In [64]:
ar2

array([[1, 5, 6],
       [3, 7, 9],
       [1, 4, 3]])

In [65]:
np.sqrt(ar)         ## squre

array([[1.41421356, 2.        , 2.23606798],
       [2.23606798, 1.73205081, 3.        ],
       [3.31662479, 2.        , 1.        ]])

In [66]:
ar.sum()

np.int64(44)

In [67]:
ar.max()

np.int64(11)

In [68]:
ar.min()

np.int64(1)

In [69]:
np.where(ar>2)

(array([0, 0, 1, 1, 1, 2, 2]), array([1, 2, 0, 1, 2, 0, 1]))

In [70]:
np.count_nonzero(ar)

9

In [71]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [72]:
ar[1,2]=0

In [73]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [74]:
import sys

In [75]:
check_ar=[0,5,52,6]

In [76]:
np_ar=np.array(check_ar)

In [77]:
sys.getsizeof(1)*len(check_ar)      ## size of python array

112

In [78]:
np_ar.itemsize*np_ar.size       ## size of numpy array

32

In [79]:
np_ar.tolist()

[0, 5, 52, 6]